<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DentaCore.Identity.Domain/DentaCore.Identity.Domain.csproj" />
    <ProjectReference Include="../DentaCore.Identity.Contracts/DentaCore.Identity.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/DentaCore.BuildingBlocks.Application/DentaCore.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
