<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DentaCore.Audit.Domain/DentaCore.Audit.Domain.csproj" />
    <ProjectReference Include="../DentaCore.Audit.Contracts/DentaCore.Audit.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/DentaCore.BuildingBlocks.Application/DentaCore.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
