<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DentaCore.Scheduling.Application/DentaCore.Scheduling.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/DentaCore.BuildingBlocks.Infrastructure/DentaCore.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
