<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../DentaCore.Sync.Domain/DentaCore.Sync.Domain.csproj" />
    <ProjectReference Include="../DentaCore.Sync.Contracts/DentaCore.Sync.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/DentaCore.BuildingBlocks.Application/DentaCore.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
